// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI9J_vjSAJ0UNY6HbMW7Bd5PqleZOV1Jg',
    appId: '1:1013754567458:web:0f701e883f659e418a637b',
    messagingSenderId: '1013754567458',
    projectId: 'nomad-ym-tiktok',
    authDomain: 'nomad-ym-tiktok.firebaseapp.com',
    storageBucket: 'nomad-ym-tiktok.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mKslOB0WKQIxsgPPICH__S_ZZ0b7LTA',
    appId: '1:1013754567458:android:5b18c507f78d5b648a637b',
    messagingSenderId: '1013754567458',
    projectId: 'nomad-ym-tiktok',
    storageBucket: 'nomad-ym-tiktok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDOs6M6W3ay6NdgomhLQDQFal--JhPgPU',
    appId: '1:1013754567458:ios:340c9fad0d15a8078a637b',
    messagingSenderId: '1013754567458',
    projectId: 'nomad-ym-tiktok',
    storageBucket: 'nomad-ym-tiktok.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}